/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  // static const String apple = "assets/images/apple.png";
  // static const String appLogo = "assets/images/app_logo.png";
  // static const String facebook = "assets/images/facebook.png";
    static const String google = "assets/image/google.png";
  // static const String inactiveBag = "assets/images/inactive_bag.png";
  // static const String inactiveCart = "assets/images/inactive_cart.png";
  // static const String inactiveHome = "assets/images/inactive_home.png";
  // static const String inactiveProfile = "assets/images/inactive_profile.png";
  // static const String inactiveWishlist = "assets/images/inactive_wishlist.png";
  // static const String addedToWishlist = "assets/images/added_to_wishlist.png";
  // static const String notAddedToWishlist =
  //     "assets/images/not_added_to_wishlist.png";
  static const String signIn = "assets/image/signin.png";
  static const String signUp = "assets/image/signup.png";
  static const String welcome = "assets/json/welcome.json";
  static const String lossInternet = "assets/json/internetloss.json";
  // static const String splashWeb = "assets/json/splash_web.json";
  // static const String homeBanner = "assets/images/home_banner.png";
}
